### ISSUE TITLE
金银礼物这个插件有错误

### ISSUE THREAD

**Issue by youth1996** [lzghzr/bililive_dm_plugins#1]
可能因为之前的改版原因，现在包裹礼物确实显示包裹，银瓜子礼物（辣条）会显示包裹，金瓜子礼物（爆竹）后面没有显示。
![tim 20180130093220](https://user-images.githubusercontent.com/32319709/35543551-ad2b381e-05a0-11e8-8caf-9207ab6d1f0b.png)
这是赠送银瓜子礼物时显示。
![tim 20180130093224](https://user-images.githubusercontent.com/32319709/35543552-ad61458a-05a0-11e8-9bf4-71c5bb35b9b0.png)
这是赠送爆竹时的显示。

**Comment by lzghzr** [comment]
因为B站似乎修复了这个错误，原来的方法已经不能区分礼物来源了，readme上有写

**Comment by youth1996** [comment]
懂了，原来说的修复是这个意思啊。

**Comment by lzghzr** [comment]
话说现在金银礼物都分开了，这个插件也没必要了把，最多分一下辣条来源（还是能做到的）
白嫖的我给B站丢脸了

**Comment by youth1996** [comment]
嗯，是没太大用处（我也只是观众，看着玩的），就是偶然发现这三个插件，发现了这个问题，现在只需要区分一下是不是包裹的礼物就行。

**Comment by lzghzr** [comment]
更新了以下，应该可以正常使用了

**Comment by youth1996** [comment]
嗯，之前看见更新以后自己编译了，谢谢
